# An image will be captured every this many simulation ticks.
# The FPS of the camera is base_freq / camera_period
camera_period: 10
lidar_period: 20

should_do_depth: false
carla_hostname: localhost
carla_port: 2000

camera_params:
  fov: 90  # Field of view in degrees
  width: 720
  height: 480

# All transforms are in the conventional ROS coordinate frame
#  (according to https://www.ros.org/reps/rep-0103.html#coordinate-frame-conventions):
#  - x: Forward
#  - y: Left
#  - z: Up (along optical axis of camera)
# Rotations are in degrees:
#  - roll: Positive right (Around +x axis)
#  - pitch: Positive down (Around +y axis)
#  - yaw: Positive left (Around +z axis)

# Transform from vehicle frame to IMU0 frame (which is also the frame for Rovio)
imu0_transform:
  x: 2.5
  y: 0.0
  z: 1.8
  roll: 0
  pitch: 0
  yaw: 0

# Transform from vehicle frame to Camera frame
camera_transform:
  x: 2.5
  y: 0.0
  z: 1.8
  roll: 0
  pitch: 0
  yaw: 0

# Transform from vehicle frame to IMU1
imu1_transform:
  x: 2.5
  y: 0.0
  z: 1.8
  roll: 0
  pitch: 0
  yaw: 0

# Transform from vehicle frame to Lidar
lidar_transform:
  x: 2.5
  y: 0.0
  z: 1.8
  roll: 0
  pitch: 0
  yaw: 0