sensors:
  lidar:
    sensor_topic: "/lidar"
    sensor_type: "PointCloud2"
#    odom_topic: "/aft_mapped_to_init_CORRECTED"
#    odom_topic: "/laser_odom_to_init_CORRECTED"
    odom_topic: "/gtsam_fusion_filter/laser_odom_output"
    optimize_after_odom: true
    use_odom_covariance: false
    covariance_linear: 0.00001
    covariance_angular: 0.000001
    max_time_skip: 0.1
  vio:
    sensor_topic: /cam0/image_mono
    sensor_type: "Image"
    odom_topic: /rovio/odometry
    optimize_after_odom: false
    use_odom_covariance: false
    covariance_linear: 0.01
    covariance_angular: 0.001
    max_time_skip: 0.1
imu:
  topic: "/imu/fusion"
  cov_bias_acc: 0.0001
  cov_bias_omega: 0.000001
  cov_accel: 0.000001
  cov_gyro: 0.000001
  cov_integration: 0.0000001
  cov_bias_acc_omega_int: 0.0001
tf:
  static_frame: "/rovio_world"
  odom_frame: "/gtsam_odom"
filter:
  rot_degen_threshold: 11.0
  trans_degen_threshold: 27.0
