sensors:
  lidar:
    sensor_topic: /lidar
    sensor_type: "PointCloud2"
    odom_topic: /aft_mapped_to_init_CORRECTED
    use_odom_covariance: false
    covariance_linear: 0.1
    covariance_angular: 0.01
#  vio:
#    sensor_topic: /cam0/image_mono
#    sensor_type: "Image"
#    odom_topic: /rovio/odometry
#    use_odom_covariance: false
#    covariance_linear: 0.1
#    covariance_angular: 0.01
imu:
  cov_bias_acc: 0.0001
  cov_bias_omega: 0.0001
  cov_accel: 0.0001
  cov_gyro: 0.0001
  cov_integration: 0.0001
