sensors:
  lidar:
    sensor_topic: /lidar
    sensor_type: "PointCloud2"
    odom_topic: /aft_mapped_to_init_CORRECTED
    optimize_after_odom: true
    use_odom_covariance: false
    covariance_linear: 0.00001
    covariance_angular: 0.000001
  vio:
    sensor_topic: /cam0/image_mono
    sensor_type: "Image"
    odom_topic: /rovio/odometry
    optimize_after_odom: true
    use_odom_covariance: false
    covariance_linear: 0.00001
    covariance_angular: 0.000001
imu:
  topic: "/imu/fusion"
  cov_bias_acc: 0.000001
  cov_bias_omega: 0.000001
  cov_accel: 0.01
  cov_gyro: 0.01
  cov_integration: 0.0001
